### ISSUE TITLE
`lesson-figures` rule is missing from Makefile

### ISSUE THREAD

**Issue by gcapes** [carpentries/lesson-example#222]
In the MATLAB lesson, currently the first three images in the `extras/figures` page have been deleted. 

I was going to rebuild that page, but the Makefile is missing the rule to do so (as described here: http://carpentries.github.io/lesson-example/07-checking/index.html#displaying-figures)

This repo is also missing the described rule and python script. Is there a new way to do this, and if so what is it?

Thanks

**Comment by maxim-belkin** [comment]
`lesson-figures` has been replaced by a (Java) script by @rgaiacs back in November last year.
Related commit: 47bfe1bdb97f7925ace52ed71aa93ba828c709f7

Matlab repo has to copy file `bin/boilerplate/_extras/figures.md` to `_extras`

**Comment by gcapes** [comment]
Great, thanks.
However, that doesn't completely resolve this issue, which is that the instructions (at the link above) don't match with the current implementation.

**Comment by rgaiacs** [comment]
@gcapes Thanks for the comment.

> the instructions (at the link above) don't match with the current implementation.

carpentries/lesson-example#223 fix the instructions.
