### ISSUE TITLE
Remove .gitkeep files & where necessary, add READMEs explaining why empty folder is tracked

### ISSUE THREAD

**Issue by katrinleinweber** [carpentries/lesson-example#234]
I first encountered `.gitkeep` files in the context of the Carpentries and I came to wonder whey they are used at all? In [_episodes_rmd/data](https://github.com/carpentries/lesson-example/tree/gh-pages/_episodes_rmd/data) for example, or in [_episodes](https://github.com/carpentries/lesson-example/tree/gh-pages/_episodes).

If we were to:

a) remove them wherever other files already make sure the folder is tracked as well, and
b) replace them with a short `ReadMe.md` that explain the purpose of an otherwise empty folder,

I think we could simplify and clarify our lesson (and [workshop](https://github.com/carpentries/workshop-template/)!) directory structure. What do you think?

PS: Over in https://github.com/swcarpentry/r-novice-inflammation/issues/398, we removed them all without adverse effects.

**Comment by rgaiacs** [comment]
@katrinleinweber Thanks to bring this up. Is a great question.

> remove them wherever other files already make sure the folder is tracked as well

Extra work to restore the `.gitkeep` if we remove the files.

> replace them with a short `ReadMe.md` that explain the purpose of an otherwise empty folder

`README.md` can mess up with Jekyll plus is one extra place to keep our documentation in place.

**Comment by katrinleinweber** [comment]
> Extra work to restore the .gitkeep if we remove the files.

How often does that situation occur? If it does, there should be an explanation why the folder has to be kept, anyway => See below.

> keep our documentation in place.

Just 1 sentence explaining why that empty folder is needed ;-) Or even just a file with a more explanatory name then "keep".

**Comment by fmichonneau** [comment]
They can be removed once the folder structure of the repository is set, but are needed when importing the template the first time.

We mention `.gitkeep` files in the [SWC git lesson](http://swcarpentry.github.io/git-novice/04-changes/index.html#directories), and it's a fairly standard practice.

Improvements to the documentation are always welcome!
