### ISSUE TITLE
Figure forking.svg in episode 2 is either confusing or wrong

### ISSUE THREAD

**Issue by IgnasiLucas** [carpentries/lesson-example#250]
The diagram represents the ideal organization of repositories. Its header "swcarpentry  User_X  User_Y" seems to indicate the owners of the repositories aligned underneath. However, under "User X" there is one repository labeled as user X's copy of lesson A, and one labeled as user Y's copy of lesson B. The same is true for the repositories aligned under "User Y". I suppose there is a mistake in the repository's labels, rather than in the header of the diagram. This is because I understand that either user may want to copy more than one lesson, instead of each lesson being copied twice by the same user.

Before submitting a pull request, I would like confirmation that I understood it properly. If so, I should probably edit the text as well. Below the diagram, the text explains that "GitHub only allows a user to have one fork of any particular repo". But I don't see how this prevents an author from contributing to several lessons. If anything, the problem seems to be that lessons master copies cannot all be forks of the template repository.

**Comment by katrinleinweber** [comment]
Yeah, there seems to be a row vs. colum error in the images.

About the last part: GitHub's limit there would prevent the Carpentries from having multiple lesson repos all forked from the same master in the first place.

If you send a PR, I would additionally suggest to rename `template` to `styles` and to see whether including links to https://carpentries.github.io/lesson-example/setup.html and https://github.com/carpentries/lesson-example/blob/gh-pages/CONTRIBUTING.md#using-github are feasible.

**Comment by mpcox** [comment]
I think I've managed to fix this. See what you think?

**Comment by mpcox** [comment]
I wasn't sure how to add the links to the image. Did you literally mean writing them on the figure itself? They're quite long. Thoughts?

**Comment by katrinleinweber** [comment]
The links were meant for the text ;-)

**Comment by mpcox** [comment]
Ah! In that case, I've added the links into a section at the beginning of the lesson called 'Background Resources'. I'm not sure if that's the right place for them, but it seemed like the best option...?
