### ISSUE TITLE
Contribution guidelines link broken

### ISSUE THREAD

**Issue by maneesha** [carpentries/lesson-example#254]
Link to contribution guidelines from http://carpentries.github.io/lesson-example/ is broken.

**Comment by maxim-belkin** [comment]
Maneesha, fixing the link is easy, however... Could you please provide some context for your direct commits to this repository starting with 8067917164b8e5b717772c4a5505c656d4936095? They introduced significant changes that I don't recall being reviewed/discussed in the public. If the decision was made to deprecate this lesson, you can archive it and add a corresponding note to the README.

**Comment by maneesha** [comment]
@maxim-belkin   These changes came from a project that @ErinBecker  is managing. She can tell you more about the context of this and how the decisions were made.

**Comment by maneesha** [comment]
Closing - fixed with db5c733567550cc9df34cecb7bd09212c64edaff

@maxim-belkin  If you want to discuss the larger changes made here you can do so in this issue: #256
