### ISSUE TITLE
Add "R for Reproducible Scientific Analysis" to syllabus

### ISSUE THREAD

**Issue by maxim-belkin** [carpentries/lesson-example#268]
"R for Reproducible Scientific Analysis" is not in the SWC Syllabus file (_includes/sc/syllabus.html)
CC @naupaka

**Comment by naupaka** [comment]
I am not sure if this is still the most current template in use for generating new lessons? Maybe @fmichonneau knows more?

**Comment by maxim-belkin** [comment]
Yeah, I should've submitted this PR to the styles repo...

**Comment by maxim-belkin** [comment]
Moved to carpentries/styles#404
