### ISSUE TITLE
Liquid question: What is {{ page.root }}

### ISSUE THREAD

**Issue by wirawan0** [carpentries/lesson-example#275]
Hi, this is more of a question than an issue, but I am putting it here because I believe this community can answer it. While working on Carpentry lesson, I noticed the extensive use of {{page.root}} in the lesson source. For example, the `02-tooling.md` has this text:

    The master copy of each lesson would be a fork of that repo,
    and each author's working copy would be a fork of that master:

    ![Forking Repositories]({{ page.root }}/fig/forking.svg)

    However, GitHub only allows a user to have one fork of any particular repo.

My question is, what is this `page.root` jekyll variable? I am very confused because on Jekyll manual on the built-in variables, <https://jekyllrb.com/docs/variables/> , there is no reference to `page.root` variable at all. Neither could I find a reference to it on Google. Can somebody give an explanation, as well as a reference/site that mentions it?

Wirawan

**Comment by fmichonneau** [comment]
the value of the `page.root` variable is defined within the `_config.yml` (https://github.com/carpentries/lesson-example/blob/gh-pages/_config.yml#L77-L92) and is a trick to get the depth of the page compared to the root. It mostly works.

**Comment by wirawan0** [comment]
Thanks for clarifying, Francois!

**Comment by gcapes** [comment]
Sorry to be slow, but *where* is the value given? Somewhere this must resolve to either a local address or the github URL. How could I extract the github URL?

**Comment by fmichonneau** [comment]
If you use a reasonably recent version of the template it's in the `_config.yml` file: https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/_config.yml#L77-L92 

Some pages have it defined in their yaml headers instead.

Where would you like to extract the GitHub URL? if it's from within the jekyll site itself, then the GitHub metadata provided by this plugin (https://github.com/jekyll/github-metadata) might be helpful.

**Comment by gcapes** [comment]
Thanks for the reply.

I have [this code](https://github.com/gcapes/exercise-extractor), which extracts the exercises from the markdown files in the `_episodes` folder. I'm wanting this mainly for the instructor training repo. It needs to be able to substitute the actual URLs in place of the variables in the markdown.

Now I can get some of the variable values easily from the [_config.yml](https://github.com/carpentries/instructor-training/blob/gh-pages/_config.yml) file, such as `swc_site`, because that is in the yaml file: https://github.com/carpentries/instructor-training/blob/gh-pages/_config.yml#L45

What I can't figure out is what the value of e.g. `{{page.root}}` is. Lines 77-92 that you linked to in the same yaml file don't mean anything to me, and don't contain the URL which in this case would be `https://carpentries.github.io/instructor-training/`.

So the question is, where can I read this value from?

**Comment by maxim-belkin** [comment]
> What I can't figure out is what the value of e.g. `{{page.root}}` is.

Add `{{ page.root }}` (or any other variable) anywhere in the page you're working with and it will be displayed in the rendered version. You can always push to `gh-pages` branch of your-fork to see the effect of your changes on GitHub.

**Comment by gcapes** [comment]
Sorry, I'm not being as clear as I could be. I have seen what this variable does, but I want to be able to *read* the value programmatically. Where is the value stored? I know that it evaluates to `localhost:whatever` when building pages locally, and https://swcarpentry.github.io/whatever on github. Can I read the latter value from somewhere?

**Comment by maxim-belkin** [comment]
>  Where is the value stored?

This is what @fmichonneau was trying to explain:
Default values for `page.root` are defined in [_config.yml](https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/_config.yml#L77-L92):
 - the _"true"_ default value is "."
    ```
    defaults:
      - values:
          root: .
          layout: page
    ```
 - for "episodes" it is ".."
    ```
      - scope:
          path: ""
          type: episodes
        values:
          root: ..
          layout: episode
    ```
 - for "extras" it is (also) ".."
    ```
      - scope:
          path: ""
          type: extras
        values:
          root: ..
          layout: page
    ```
It can also be set on a "per page" basis in the "front matter", e.g.:
```
---                                                                                                     
layout: lesson
root: .
permalink: some_page.html
--- 
```

**Comment by fmichonneau** [comment]
@gcapes I think you're right and there is no way of getting this URL from the content of the repo. For this, we rely on the GitHub metadata as provided by the Jekyll plugin I mentioned above. Could you also get it where the plugin is getting it: using the GitHub API (see https://developer.github.com/v3/repos/#get and the `homepage` key in the returned JSON).

**Comment by maxim-belkin** [comment]
Websites can be published anywhere so unless we write down the url somewhere -- there is no way of telling where it is published.

If you intend your script to be used locally, you can "hack" it like so:
In the `_config.yml` file read the value of "carpentry": "swc", "dc", or "lc". It tells you which URL prefix to use (value of `swc_pages` for "swc", value of `dc_site` for "dc", and value of `lc_site` for "lc"). Then, you can parse the value of `git config --local remote.origin.url` to get the lesson suffix.

If you want your script to run "online" you should switch to Javascript.

**Comment by gcapes** [comment]
Thanks both. I've got it sorted now using a variation of @maxim-belkin's suggestion.
