### ISSUE TITLE
How do do multiday schedules?

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-example#279]
Is there someplace to look for multi-day schedules in the lesson?  I can see it in the `_includes/syllabus.html` file that this seems to be possible but I'm unclear on how to set it up correctly

Thanks!
Sarah

cc: @cmilica

**Comment by agitter** [comment]
@sstevens2 my best guess based on the following is that it is controlled by the episode attributes
https://github.com/carpentries/lesson-example/blob/400216b95cfcbcaf09364ae0266cd21c6685a3ac/_includes/syllabus.html#L13-L15

So the first episode of each new day would have
```
start: true
```
in its header.  I haven't tested this though.  Can anyone confirm whether this is correct?

**Comment by sstevens2** [comment]
@fmichonneau or @ErinBecker do you have any suggestions for this?  I did play around with the multiday options but I couldn't get it to work.

**Comment by fmichonneau** [comment]
this might be fixed in https://github.com/carpentries/workshop-template/pull/706 
Please re-open the issue if it is not the case. Thanks!
