### ISSUE TITLE
Recommend using a newer version of Ruby for those wanting to test locally?

### ISSUE THREAD

**Issue by willfurnass** [carpentries/lesson-example#289]
```
$ rbenv install 2.5.3
Downloading ruby-2.5.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.3.tar.bz2
Installing ruby-2.5.3...

WARNING: ruby-2.5.3 is nearing its end of life.
It only receives critical security updates, no bug fixes.
```

Not sure which Ruby version to recommend as not a Ruby dev.

**Comment by brownsarahm** [comment]
Thanks @willfurnass! 

We are limited to using the version that github supports, but it does look like they have updated to 2.5.8 [Github pages version](https://pages.github.com/versions/). We will update these [instructions](https://carpentries.github.io/lesson-example/setup.html#jekyll-setup-for-lesson-development) after we confirm that this works with our styles repo without issue. I'll open an issue there to start that.

**Comment by fmichonneau** [comment]
thanks for spotting this @willfurnass!
I updated the instructions to list the currently used version of Ruby by Github pages which is 2.5.8.
