### ISSUE TITLE
Revise (slightly) order of Setup

### ISSUE THREAD

**Issue by kekoziar** [carpentries/lesson-example#290]
When walking through the setup, the section that helps install Jekyll is slightly hidden, and not encountered until near the end of the lesson setup process.  Installing it at this point interrupts the flow of setting up and checking the lesson. Perhaps under the *Requirements* section, instead of linking to Jekyll site, it can link to an anchor at the Jekyll installation instructions which live at the bottom of the page.  Perhaps also include text "See Jekyll Setup below" as a prompt.  This way, everything can be installed prior to walking through the lesson setup process.

**Comment by fmichonneau** [comment]
Thanks for the suggestion @kekoziar, it's a good idea. I'll put in a pull request soon to address this!
