### ISSUE TITLE
Travis CI failing: subprocess.Popen has no argument 'encoding'

### ISSUE THREAD

**Issue by willfurnass** [carpentries/lesson-example#297]
With commit  3107239 (latest commit on `gh-pages` branch):

```
The command "bundle install" exited with 0.
0.14s$ make lesson-check-all
Traceback (most recent call last):
  File "bin/lesson_check.py", line 566, in <module>
    main()
  File "bin/lesson_check.py", line 116, in main
    check_source_rmd(args.reporter, args.source_dir, args.parser)
  File "bin/lesson_check.py", line 201, in check_source_rmd
    data = read_markdown(parser, f)
  File "/home/travis/build/carpentries/lesson-example/bin/util.py", line 120, in read_markdown
    close_fds=True, universal_newlines=True, encoding='utf-8')
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

Think this may be due to the `encoding` kw arg [being introduced in Python 3.6](https://docs.python.org/3/whatsnew/3.6.html#subprocess) but Ubuntu 16.04, as used by the Travis CI jobs, shipping with Python 3.5.

**Comment by maxim-belkin** [comment]
Thanks for the report, Will! We indeed need Python 3.6+. Could you please check if adding something like
```
python: 
 - 3.6
```
or `python: 3.6` to the .travis.yml file (and removing `python3.5 python3-pip` from line 34) solves the problem?

**Comment by willfurnass** [comment]
That didn't work (possibly due to `language: r` below?)  Subsequently tried switching to `dist: bionic` but now having [problems with installing R](https://twitter.com/WillFurnass/status/1296129518227394565)...

**Comment by maxim-belkin** [comment]
@fmichonneau created #299 which will sync the [`.travis.yml`](https://github.com/carpentries/lesson-example/pull/299/commits/7a0bb5fdac0d5dccb66f8e2947e625f0c0614b58#diff-354f30a63fb0907d4ad57269548329e3) in this repository with the one in carpentries/styles. You might want to change the new file when #299 is merged.

**Comment by fmichonneau** [comment]
closing as stale as we are now using GitHub Action
