### ISSUE TITLE
Homebrew install command for Mac has been deprecated

### ISSUE THREAD

**Issue by eldobbins** [carpentries/lesson-example#322]
In the [Set-up](https://carpentries.github.io/lesson-example/setup.html) instructions, the command to install Homebrew on a Mac is:

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

I ran into 2 problems running that on my Mac

* I needed to run it using sudo
* After getting sudo privileges, running the command gave the following error:
> Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
> Bash. Please migrate to the following command:
>  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
>
> Don't run this as root!

So this worked to install and use ruby 2.7.2 (my Mac had a previous version of ruby):

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew install ruby
echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> /Users/liz/.bash_profile
```

Note: I was also having trouble with `rbenv`, but I think this command solved it:
```
sudo xcode-select --reset
```
but I'm not sure if that's a global problem or just some conflict with what else I have installed on my computer.

**Comment by maxim-belkin** [comment]
Hi Liz,
You're correct that the command to install Homebrew has changed and now uses `install.sh`. Would you like to open a PR to fix that?

As for Ruby --  do you remember the error message you got that required `xcode-select --reset`? Depending on how common this problem is, we might want to mention it in the setup. On a related note, I think we can assume that lesson developers don't have Xcode installed initially, so it might be good to mention `sudo xcode-select --install`.

**Comment by fmichonneau** [comment]
Thanks for the report Liz. I updated the command and added a sentence to check the installation instruction page listed on the Homebrew site. `sudo` shouldn't be needed according to them. However, I don't have a mac system to test things out.

**Comment by fmichonneau** [comment]
@maxim-belkin we looked at this at the same time I guess :) 

Good point about Xcode, Liz let us know if you think we should provide more info about this.

**Comment by eldobbins** [comment]
I don't think more information about Xcode is needed. I think it was an error peculiar to my machine.  In May, I tried to to use Conda to install ruby, and I think that may have left things unordered.  If other people have trouble installing on Macs, we can revisit this.

**Comment by maxim-belkin** [comment]
Thanks for the note, Liz! I agree that the need to use `xcode-select --reset` stems from previous interactions with this command. Let's see if we get more reports about this command.
