### ISSUE TITLE
migrate setup-ruby from actions to ruby

### ISSUE THREAD

**Issue by tkphd** [carpentries/lesson-example#332]
https://github.com/carpentries/lesson-example/blob/2a25bb300e1fdd47f62aff20244876f3891a82c2/.github/workflows/template.yml#L36

[actions/setup-ruby](https://github.com/actions/setup-ruby) is deprecated, with the following message:

> Please note: This action is deprecated and should no longer be used. The team at GitHub has ceased making and accepting code contributions or maintaining issues tracker. Please, migrate your workflows to the ruby/setup-ruby, which is being actively maintained by the official Ruby organization.

**Comment by maxim-belkin** [comment]
This has been addressed in the carpentries/styles repo (https://github.com/carpentries/styles/commit/ed77edaea17ac700970da9388d489256d5e3494e). This message should go away after you sync your lesson with the styles repository.

**Comment by tkphd** [comment]
That's good, and I will. The linked file is in *this* repo, though, and others may source this repo as the upstream for the GitHub workflow definitions.

**Comment by maxim-belkin** [comment]
This repo got this file from the carpentries/styles repo.

**Comment by tkphd** [comment]
OK.
