### ISSUE TITLE
404 page does not render correctly for any arbitrary invalid URL

### ISSUE THREAD

**Issue by jhlegarreta** [carpentries/lesson-example#335]
The 404 page seems to work correctly when introducing an invalid URL from the main page, e.g.
https://carpentries.github.io/lesson-example/random

However, the style is not correctly applied when introducing an invalid URL from any other page/episode or any other part of the URL, e.g.
https://carpentries.github.io/lesson-example/03-organization/index1.html
https://carpentries.github.io/lesson-example/03-organization1/index.html

**Comment by maxim-belkin** [comment]
Thanks @jhlegarreta. Could you please submit the issue (and the fix) to carpentries/styles?

**Comment by jhlegarreta** [comment]
@maxim-belkin Unfortunately, I do not know what the fix is :pensive:, but I can open the issue in the carpentries/styles and close it here if that is the right place for the issue.

**Comment by maxim-belkin** [comment]
Ah, OK. I assumed that the linked (merged) pr has a fix. Yes, please submit it to carpentries/styles.

**Comment by jhlegarreta** [comment]
Keeping track of the issue in https://github.com/carpentries/styles/issues/568

Closing.
