### ISSUE TITLE
Document katex math support

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-example#345]
The template now supports rendering of equations in LaTeX syntax and this should be documented in the Lesson Example. I believe the appropriate place would be `04-formatting.md`.

**Comment by CunliangGeng** [comment]
The equations in example lesson are not properly rendered: 
![image](https://user-images.githubusercontent.com/9798985/204777601-a3eaca94-77f1-4556-b641-df93d40d08d6.png)

**Comment by tobyhodges** [comment]
@zkamvar I wonder if we should remove the section from the Lesson Example documentation? It's a relatively quick "fix" that will prevent people from running into the same problem again between now and April.

**Comment by GuillermoFidalgo** [comment]
I agree with @tobyhodges and think we should document a solution like @zkamvar has listed above. That solution did not seem to fix it for me.

Maybe just mention that adding the following at the top of the `.md` files where math is needed should be enough.

```
<script type="text/javascript" async
src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```
