### ISSUE TITLE
Broken link Github where to contribute page

### ISSUE THREAD

**Issue by wrawra90** [carpentries/lesson-example#347]
The link provided on the “how to contribute” section on the GitHub page [https://github.com/carpentries/lesson-example/blob/9d93e4c8a27b5c5f43179ba8d927903bf9533cdd/CONTRIBUTING.md](url) is broken. 

The broken link is under the heading "where to contribute" and is written as [https://github.com/swcarpentry/FIXME](url) which leads to 404 error message. 

This link is also under the suggested "contributing guidelines" which pops up in github if it is someones first contribution:
<img width="256" alt="Screen Shot 2021-06-18 at 3 12 30 pm" src="https://user-images.githubusercontent.com/86093274/122509739-9cfcca00-d047-11eb-8602-08ed9d3ff5b2.png">

**Comment by maxim-belkin** [comment]
Thanks for the report, @wrawra90! It should be fixed now.
