### ISSUE TITLE
How to link to episode from setup?

### ISSUE THREAD

**Issue by gcapes** [carpentries/lesson-example#367]
I'm struggling with this on one of my lessons. It works locally but not on GitHub.

My [setup page](http://gcapes.github.io/git-course/setup.html) uses a link "set up ssh keys". [Page source](https://github.com/gcapes/git-course/blob/gh-pages/setup.md).

Locally this resolves to http://127.0.0.1:4000/08-remote/index.html/#set-up-ssh-keys, but on GitHub it resolves to http://gcapes.github.io/08-remote/index.html/#set-up-ssh-keys i.e. it is missing the repo name (git-course). I need it to resolve to http://gcapes.github.io/git-course/08-remote/index.html/#set-up-ssh-keys

This repo gives [instructions](https://carpentries.github.io/lesson-example/04-formatting/index.html#locations-and-names) on how to link from an episode to another, but not from setup. I think `page.root` refers to the directory containing the current page which is not what I need here, but I can't figure out what I'm doing wrong.

My repo might well have some old stuff complicating the picture like the permalink in the yaml front matter. 

Anyone able to put me out of my misery?

**Comment by maxim-belkin** [comment]
Does `{{ page.root }}/{% link _episodes/08-remote.md %}/#set-up-ssh-keys` work?

**Comment by maxim-belkin** [comment]
Try using `{{ relative_root_path }}` instead of `{{ page.root }}`. `relative_root_path` is defined in `_includes/base_path.html`.

**Comment by tobyhodges** [comment]
Hey @gcapes, I forked your repo and found that I could get the link to resolve correctly locally, on GitHub Pages, and in an "offline" build of the site (with `make site`) by using `page.root` and removing the slash before the anchor in the link i.e.

```
[set up SSH keys]: {{ page.root }}{% link _episodes/08-remote.md %}#set-up-ssh-keys
```

Check out my version at https://github.com/tobyhodges/git-course/blob/gh-pages/setup.md and https://tobyhodges.github.io/git-course/setup.html

**Comment by gcapes** [comment]
Thanks @tobyhodges and @maxim-belkin 

This now works for me too. I have no idea why it didn't seem to before. I tried lots of stuff locally and remotely (hidden in force pushes). Must be some sort of new year related 'user error' on my part :)
