### ISSUE TITLE
Add description of publication procedure

### ISSUE THREAD

**Issue by gvwilson** [carpentries/lesson-example#85]
Explain when and how we publish lessons and assign authorship/editorship credit.

**Comment by wking** [comment]
On Wed, Dec 21, 2016 at 04:24:49AM -0800, Greg Wilson wrote:
> Explain when and how we publish lessons and assign
> authorship/editorship credit.

Some relevant blog posts and the bug-BBQ site:

https://software-carpentry.org/blog/2016/10/close-cousins.html
https://software-carpentry.org/blog/2016/07/publishing-lessons.html
https://software-carpentry.org/blog/2016/05/may-lab-meeting.html
http://swcarpentry.github.io/SWC-bug-bbq/
https://software-carpentry.org/blog/2015/09/publishing-our-lessons.html
https://software-carpentry.org/blog/2015/06/update-on-publishing-lessons.html
https://software-carpentry.org/blog/2015/04/publishing-our-lessons.html

**Comment by rgaiacs** [comment]
@twitwi I now that you are working on this so I will assign it to you. :-) Thanks in advance.
